# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-11 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('WSniffer', '0002_delete_wsniffer'),
    ]

    operations = [
        migrations.CreateModel(
            name='WSniffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ApMac', models.CharField(max_length=100)),
                ('ApSsid', models.CharField(max_length=100)),
                ('StaMac', models.CharField(max_length=100)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('HttpRequestHeader', models.TextField(max_length=5000)),
                ('NatIp', models.CharField(max_length=100)),
                ('NatPort', models.CharField(max_length=100)),
            ],
        ),
    ]
